### ISSUE TITLE
滚动不了页面

### ISSUE THREAD

**Issue by Yexi** [hoochanlon/fq-book#25]
# 超出单页的内容无法看

**Comment by Holit** [comment]
Try to access with Internet Explorer.
It works on me.

**Comment by hoochanlon** [comment]
说中文难道不香吗？
![](https://i.loli.net/2020/03/08/EQNzvRMLagwTU2D.gif)

**Comment by Holit** [comment]
使用IE访问就可以了。
至少对我有用
另外X还是要装一下的😂

**Comment by Yexi** [comment]
> 使用IE访问就可以了。
> 至少对我有用
> 另外X还是要装一下的

大佬，弱弱的问一下，Mac有IE吗

**Comment by Holit** [comment]
> > 使用IE访问就可以了。
> > 至少对我有用
> > 另外X还是要装一下的
> 
> 大佬，弱弱的问一下，Mac有IE吗

不知道，没用过Mac
