### ISSUE TITLE
这本书

### ISSUE THREAD

**Issue by drxionger** [hoochanlon/fq-book#28]

**Comment by vigoroushui** [comment]
您好，我是徐宇辉。我已收到您的邮件，会尽快回复！

**Comment by drxionger** [comment]
？

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by hoochanlon** [comment]
一个mark项目的。

还有个莫名其妙的回复，可能发错位置了。不是的话，可能为搞营销。

无聊。
